### ISSUE TITLE
Improve `list-group` Component

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver-design#11]
- [ ] Remove `list-group` full border, only bottom border
- [ ] Add "last-child" element to `list-group` to hide the bottom border

**Comment by dennisreimann** [comment]
This sounds like the [list group flush variant](https://getbootstrap.com/docs/5.1/components/list-group/#flush).

**Comment by dstrukt** [comment]
Oh, interesting, I guess I should spend more time looking through BS5 .. or maybe this is a component I've completely missed.

I think this is exactly what I'm looking for.
