### ISSUE TITLE
Improve checkbox component

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver-design#21]
- [ ] Increase checkbox size & states

Still debating if I want the checkbox to sit vertically at the top or in the middle (like the switch component), a minor tweak we could decided upon when implementing ... but regardless.

<img width="504" alt="Screen Shot 2022-03-10 at 5 35 12 PM" src="https://user-images.githubusercontent.com/6250771/157787170-2308af63-4466-4f1f-a675-f533fa33fb69.png">

**Comment by dstrukt** [comment]
Updates

**Comment by dennisreimann** [comment]
Shall we replace the box-shadow that the focused inputs currently have with the green border also?

How should this translate to dark mode?

**Comment by dstrukt** [comment]
Hopefully this should answer some questions .. would like to improve some of the :focused states as well, but I'm going to take a look at the code changes you make so I can learn from that and submit some PRs as well, as this isn't the most exciting work I know :)

Have had to do accessibility stuff (I'm sure we're breaking a few rules there as well, intend to adjust some colors, but after we hook everything up) ... and it's even less fun.

<img width="1222" alt="Screen Shot 2022-04-02 at 4 26 09 AM" src="https://user-images.githubusercontent.com/6250771/161380987-f49a63e8-7e3e-4589-a81c-bc76621a56c8.png">
