### ISSUE TITLE
Improve toggle switch

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver-design#22]
- [ ] Add helper text variant
- [ ] Better formatting

<img width="423" alt="Screen Shot 2022-03-10 at 5 52 24 PM" src="https://user-images.githubusercontent.com/6250771/157786796-632a751c-93ce-4bd5-ba13-22742e39f502.png">

**Comment by dstrukt** [comment]
Updates.

**Comment by dennisreimann** [comment]
What's the diffrence with the "Better formatting"?

The helper text variant can be solved with the general Bootstrap layout utilities, we do not ned to define a custom component for that imho.

**Comment by dennisreimann** [comment]
Can we close this? As far as I see we don't need to customize the component and should use the Bootstrap utils for applying the helper text.
