### ISSUE TITLE
Remove underline on link hover states

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver-design#27]
Ideally the text should adjust in either color or opacity, will update this ticket with mocks.

**Comment by dennisreimann** [comment]
Where does this occur? Sounds like a bug.

**Comment by dstrukt** [comment]
My mistake, I meant "links", was translating all of my notes I made fairly quickly and made an error.

This does not happen on the Text-Only buttons.

<img width="830" alt="Screen Shot 2022-04-07 at 3 26 08 AM" src="https://user-images.githubusercontent.com/6250771/162179003-84bad180-b75d-40fb-97ec-7f48b79ef74a.png">
