### ISSUE TITLE
Improve Currency Selector

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver-design#29]
Not 100% where the best place for this would be, so we can move to the main repo if we need to, but would be great to make this consistent with the other dropdown/select components.

Not a high priority, just flagging.

<img width="187" alt="Screen Shot 2022-04-07 at 10 19 27 PM" src="https://user-images.githubusercontent.com/6250771/162370488-c9974954-2e06-4ece-b1c8-50a02412ad18.png">

**Comment by dennisreimann** [comment]
This got updated in one of the v1.6 releases.
