### ISSUE TITLE
Improve `StoreSelector` transition consistency

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver-design#30]
Another minor issue, not 100% sure where to post, but flagging for us.

This was recorded before the latest design system changes, but don't think it'll affect the transition times.

![icon-text-offset-transition](https://user-images.githubusercontent.com/6250771/162371247-8b52b554-3fb2-4cac-a390-f940a5eaa726.gif)

**Comment by dennisreimann** [comment]
That's weird - which browser is it? For me it works in Firefox and I just checked: The button and the icon have the same `transition` values for the color. Crazy :)

**Comment by dstrukt** [comment]
Hmm, it's on Chrome, but will check it on a few different browsers.

**Comment by dstrukt** [comment]
Also the case on Safari.
