### ISSUE TITLE
Favicon inconsistency across multiple websites on Safari 14 MacOS

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-design#4]
There's favicon inconsistency across a few of our websites on Safari 14 MacOS:

- https://foundation.btcpayserver.org
- https://btcpayserver.org
- https://directory.btcpayserver.org
-  https://docs.btcpayserver.org

It should be consistent with our design system guidelines.
![Screenshot 2021-03-22 at 11 10 09](https://user-images.githubusercontent.com/36959754/111980631-dab08c00-8b06-11eb-9e73-37c4a72259aa.png)

**Comment by dennisreimann** [comment]
Fixed by now :)

![favicons](https://user-images.githubusercontent.com/886/131645825-a5d733a4-2c80-47b0-8193-a25a46b3d1ca.png)
