### ISSUE TITLE
Improve state colored table rows

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver-design#49]
As reported by wouter. 

Tracking here.

![image](https://user-images.githubusercontent.com/6250771/179463871-1b4d56f9-da9f-4541-8c76-16d1d120608d.png)

Mocks TODO.

**Comment by dennisreimann** [comment]
The `table-striped` class should not be applied here, because that leads to the slightly different colors when there are multiple `table-danger` rows (as in this case) following each other.

**Comment by hiluan** [comment]
I'd like to help. Please let me know how.

**Comment by dennisreimann** [comment]
Fixed with the recent Bootstrap upgrade.
